import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Student, AttendanceRecord, AttendanceSummary } from '../types';

export function generateParentPDFReport(
  student: Student,
  year: number,
  monthName: string,
  summary: AttendanceSummary,
  records: AttendanceRecord[]
) {
  const doc = new jsPDF();

  // Header Banner
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, 210, 35, 'F');

  // Title in Header
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('DYNAMIC TUTORIAL', 14, 18);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(251, 191, 36); // amber-400
  doc.text('Discuss & Explore', 14, 25);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text('MONTHLY ATTENDANCE REPORT', 130, 20);

  // Student Profile Info Box
  doc.setFillColor(241, 245, 249); // slate-100
  doc.roundedRect(14, 42, 182, 36, 3, 3, 'F');

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Student Name: ${student.name}`, 20, 52);
  doc.text(`Roll / ID: ${student.rollNo}`, 20, 60);
  doc.text(`Class / Grade: ${student.gradeClass}`, 20, 68);

  doc.text(`Month & Year: ${monthName} ${year}`, 115, 52);
  doc.text(`Parent Contact: ${student.parentPhone}`, 115, 60);
  doc.text(`Batch Time: ${student.batchTime || 'Standard'}`, 115, 68);

  // Attendance Summary Metrics Box
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary Overview', 14, 88);

  const summaryData = [
    ['Total Working Days', `${summary.totalDays} Days`],
    ['Days Present', `${summary.presentDays} Days`],
    ['Days Absent', `${summary.absentDays} Days`],
    ['Attendance Percentage', `${summary.percentage}%`],
  ];

  autoTable(doc, {
    startY: 92,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [2, 132, 199], textColor: [255, 255, 255], fontStyle: 'bold' },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 10, cellPadding: 4 },
  });

  // Daily Detailed Log Table
  const lastY = (doc as any).lastAutoTable.finalY || 130;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Daily Check-In / Check-Out Log', 14, lastY + 12);

  const tableRows = records.map((r, index) => [
    index + 1,
    r.date,
    r.time,
    r.type.toUpperCase(),
    r.notes || '-',
  ]);

  autoTable(doc, {
    startY: lastY + 16,
    head: [['#', 'Date', 'Time', 'Action', 'Notes']],
    body: tableRows.length > 0 ? tableRows : [['-', 'No check-in records logged for this month', '-', '-', '-']],
    theme: 'striped',
    headStyles: { fillColor: [15, 23, 42], textColor: [255, 255, 255] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 9 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.height;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Generated by Dynamic Tutorial Attendance Portal on ${new Date().toLocaleDateString()}`,
    14,
    pageHeight - 10
  );

  return doc;
}

export function generateTeacherClassPDFReport(
  className: string,
  year: number,
  monthName: string,
  summaries: AttendanceSummary[]
) {
  const doc = new jsPDF();

  // Header Banner
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 35, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('DYNAMIC TUTORIAL', 14, 18);

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(251, 191, 36);
  doc.text('Origin of Sagacity', 14, 25);

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(255, 255, 255);
  doc.text('CLASSROOM MONTHLY REPORT', 115, 20);

  // Subheader Info
  doc.setTextColor(15, 23, 42);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(`Class/Batch: ${className}`, 14, 45);
  doc.text(`Month: ${monthName} ${year}`, 120, 45);

  const tableData = summaries.map((s, idx) => [
    idx + 1,
    s.rollNo,
    s.studentName,
    s.totalDays,
    s.presentDays,
    s.absentDays,
    `${s.percentage}%`,
    s.percentage >= 75 ? 'Good' : 'Needs Attention',
  ]);

  autoTable(doc, {
    startY: 52,
    head: [['#', 'Roll No', 'Student Name', 'Total Days', 'Present', 'Absent', 'Attendance %', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [2, 132, 199], textColor: [255, 255, 255] },
    margin: { left: 14, right: 14 },
    styles: { fontSize: 9 },
  });

  const pageHeight = doc.internal.pageSize.height;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text(
    `Dynamic Tutorial Coaching Center • Confidential Teacher Report • ${new Date().toLocaleDateString()}`,
    14,
    pageHeight - 10
  );

  return doc;
}
